export default function(){
    return [
        {
            id:1,
            name:'Main',
            href:'https://madappgang.com/',
        },
        {
            id:2,
            name:'Services',
            href:'https://madappgang.com/services',
        },
        {
            id:3,
            name:'Experience',
            href:'https://madappgang.com/experience',
        },
        {
            id:4,
            name:'Foundation',
            href:'https://madappgang.com/foundation',
        },
        {
            id:5,
            name:'Team',
            href:'https://madappgang.com/team',
        },
        {
            id:6,
            name:'Blog',
            href:'https://madappgang.com/blog',
        }
    ];
};
